# WebCrawler Commander - 默認配置文件
# 根據企業級安全標準設計，支持多環境覆蓋

# 系統基礎配置
app_name: "WebCrawler Commander"
version: "1.0.0"
environment: "development"  # development/testing/staging/production

# 服務器配置
server:
  host: "0.0.0.0"          # 監聽地址
  port: 8000                # 端口號
  workers: 1               # Uvicorn工作進程數

# 數據庫配置 (生產環境使用加密存儲)
database:
  url: "postgresql://user@localhost/webcrawler"  # 示例，使用環境變數覆蓋
  pool_size: 20
  max_overflow: 30

# Redis配置 (高可用快取)
redis:
  url: "redis://localhost:6379/0"  # 示例
  cluster: false
  pool_size: 20

# 爬蟲引擎配置
crawler:
  timeout: 30.0             # 請求超時秒數
  max_concurrent: 100       # 最大併發請求數
  user_agent_rotation: true # 使用者代理輪換
  retry_attempts: 3         # 重試次數
  retry_delay: 1.0          # 重試間隔(秒)

# 代理配置
proxy:
  enabled: true             # 是否啟用代理
  validation_interval: 300  # 健康檢查間隔(秒)
  health_threshold: 0.8     # 健康得分閾值
  rotation_strategy: "round_robin"  # 輪換策略
  timeout: 10.0             # 代理請求超時

# 安全配置
security:
  jwt:
    secret: "change-me-in-production"  # 生產環境必須修改
    algorithm: "HS256"
    expiration: 3600         # token過期時間(秒)
  encryption:
    enabled: true
    key: "your-encryption-key-here"  # 生產環境加密
  cors_origins:
    - "http://localhost:3000"  # 前端域名
    - "http://127.0.0.1:3000"

# 日誌配置
logging:
  level: "INFO"             # DEBUG/INFO/WARNING/ERROR/CRITICAL
  format: "json"            # json/text
  file:
    enabled: true
    path: "logs/webcrawler.log"
    max_file_size: "10mb"
    backup_count: 5
  console:
    enabled: true
    colorize: true

# 監控配置
monitoring:
  enabled: true
  prometheus:
    enabled: true
    port: 9090
  statsd:
    host: "localhost"
    port: 8125
    prefix: "webcrawler"
  health_check:
    interval: 30            # 健康檢查間隔(秒)
    timeout: 5             # 健康檢查超時(秒)

# 數據處理配置
data_processing:
  cleanup_enabled: true
  duplicate_detection:
    enabled: true
    similarity_threshold: 0.85
  quality_scoring:
    enabled: true
    min_score: 0.7
  validation_rules:
    strict: false          # 寬鬆模式用於開發

# 數據導出配置
export:
  formats:
    - "json"
    - "csv"
    - "excel"
    - "parquet"
  compression:
    enabled: true
    algorithm: "gzip"
  max_file_size: "100mb"
  cloud_storage:
    provider: "s3"        # s3/azure/gcp/local
    bucket: "webcrawler-exports"

# 任務排程配置
scheduler:
  enabled: true
  timezone: "Asia/Shanghai"
  persistence: true
  executor:
    pool_size: 10
    max_workers: 20
  job_defaults:
    coalesce: false
    max_instances: 3
    misfire_grace_time: 30

# 資源限制配置
resources:
  max_memory_mb: 1024      # 進程最大記憶體使用
  max_cpu_percent: 80.0    # 最大CPU使用率
  max_connections: 1000   # 最大連接數
  rate_limits:
    global_rps: 1000       # 全局請求速率限制
    per_user_rps: 100      # 每用戶請求速率限制

# 第三方服務集成
integrations:
  slack:
    enabled: false
    webhook_url: ""
    channel: "#webcrawler-alerts"
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
  pii_detection:
    enabled: true                      # 是否啟用PII檢測
    provider: "local"                  # local/cloud_service
    api_key: ""
    confidence_threshold: 0.8          # 默認置信度閾值
    batch_size: 100                    # 批處理大小
    max_concurrent: 4                  # 最大並發數

    # 語言支持
    languages:
      - "zh"
      - "en"
    default_language: "auto"

    # 啟用的實體類型
    enabled_entities:
      - "PERSON"
      - "EMAIL_ADDRESS"
      - "PHONE_NUMBER"
      - "ADDRESS"
      - "CREDIT_CARD"
      - "US_SSN"
      - "IP_ADDRESS"
      - "URL"
      - "LOCATION"
      - "DATE_TIME"

    # 要檢測的文本字段
    text_fields:
      - "title"
      - "content"
      - "description"
      - "summary"
      - "body"

    # 脫敏配置
    anonymization:
      default_strategy: "masking"
      encryption_key: ""               # 生產環境從秘密管理獲取
      key_id: "default_pii_key"

      strategies:
        PERSON: "masking"
        EMAIL_ADDRESS: "masking"
        PHONE_NUMBER: "masking"
        CREDIT_CARD: "encryption"
        US_SSN: "encryption"
        ADDRESS: "replacement"
        IP_ADDRESS: "masking"
        URL: "replacement"

      custom_masks:
        email_domain_preserve: true     # 保留郵箱域名
        phone_last_four: true           # 手機保留後4位

    # 合規規則
    compliance:
      gdpr_enabled: true
      hipaa_enabled: true
      retention_days: 2555               # GDPR要求7年
      audit_level: "detailed"            # none/minimal/detailed

    # 性能配置
    performance:
      enable_caching: true
      cache_max_size: 10000
      cache_ttl_seconds: 3600
      enable_async: true

    # 監控和指標
    monitoring:
      enable_metrics: true
      stats_interval: 300               # 5分鐘統計間隔

# 開發和調試配置
debug:
  enabled: true
  log_requests: true
  profile_requests: false
  show_error_details: true

# 功能開關 (用於灰度發佈)
features:
  advanced_crawler: true
  pii_detection: true
  real_time_monitoring: true
  scheduled_exports: true
  multi_tenant: false
  audit_logging: true
