# 微博爬蟲配置
weibo_crawler:
  # 數據源設置
  data_source: "range_scan"  # 可選: range_scan, following_list

  # UID範圍設置 (當data_source為range_scan時使用)
  uid_range:
    start: 1000000000
    end: 1000100000  # 測試用小範圍，避免過大

  # Cookie設置 (微博登錄cookie)
  cookie: ""  # 設置您的微博cookie字符串

  # 請求控制
  max_concurrent: 3  # 最大並發請求數
  request_delay: 2.0  # 請求間隔(秒)
  retry_attempts: 3
  timeout: 15.0

  # 輸出設置
  csv_output_path: "data/weibo_female_users.csv"

  # 調試設置
  debug_mode: true
  log_level: "INFO"
